import { Inter } from "next/font/google";
import Sidebar from "@/app/components/Sidebar.jsx";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Timedroid.io",
  description: "Generated by sony_national",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* <footer className="items-center justify-center">Created by <Link className="text-gray-300" href="https://www.linkedin.com/in/njansony">Sony Thomas</Link></footer> */}
      </body>
      
    </html>
  );
}
