import { Inter } from "next/font/google";
import Sidebar from "@/app/components/Sidebar.jsx"
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <div className="flex flex-col md:flex-row ">
      <div 
        className="
        absolute
        top-0
        left-0
        w-full
        h-96
        bg-gradient-to-br
        from-pink-400
        to-[#0055D1]
        -z-50
        rounded-md
        filter
        blur-3xl
        opacity-50
        "
        />
        <div className="md:flex w-[15%] ">
          <Sidebar />
        </div>
        <div className="flex-1">
        {children}
        </div>
        
        </div>
    
  );
}
